database_name="phishing_data"
collection_name="phishing_data"
data_file_name="phisingData.csv"
data_file_folder_name="phishingdata"
test_data_file_name="testData.csv"
predictions_folder_name="predictions"
predictions_file_name="predictions.csv"